### PR TITLE
New file system!

### PR DESCRIPTION
**Pull request by falsisdev**
### I tested it...

### CODE REVIEW

**Comment by falsisdev** [comment]
Wait, I deleted the index.js file for the new file system and so there is conflict :D?

**Comment by 3STEB4N28** [comment]
Ill love to put everything in the src folder but i cant, 1. I use VSC using web rip (from a website) and it doesn’t work the same way it does as a desktop app. 2. I dont wanna delete the current files since there’s a knot of changes for v 1.0.0-beta.

**Comment by 3STEB4N28** [comment]
Theres a lot*

**Comment by falsisdev** [comment]
k

**Pull request closed without merging**
